### 1.获取授权码
POST  http://127.0.0.1:33401/oauth2/authorize?client_id=67601992f3574c75809a3d79888bf16e&response_type=code&scope=message.read&redirect_uri=http%3A%2F%2F127.0.0.1%3A8090%2Fauthorized


### 2.获取token
POST  http://127.0.0.1:33401/oauth2/token?client_id=67601992f3574c75809a3d79888bf16e&client_secret=67601992f3574c75809a3d79888bf16e&grant_type=authorizationn_code&scope=profile&code=46ge_TeI-dHuAnyv67nVmCcAmFgCVSZAqjTi9Om-1aA=&redirect_uri=http%3A%2F%2F192.168.101.10%3A8847%2Ftaotao-cloud-upms%2Fopen%2Fauthorized


###
http://127.0.0.1:9800/oauth/authorize?client_id=third_client_1&client_secret=123456&response_type=code&scope=all
http://127.0.0.1:9800/oauth/token?client_id=third_client_1&client_secret=123456&grant_type=authorization_code&redirect_uri=http://www.baidu.com&code=TkWDrU
